all:
  sympal_config:
    theme:
      enabled:    true
    
    themes:
      default:
        available: true
        disabled: false
        layout: default
        stylesheets:
          - /sfSympalThemePlugin/css/default.css

      wordpress_default:
        available: true
        disabled: false
        layout: wordpress
        stylesheets:
          - /sfSympalThemePlugin/css/wordpress.css

      sympal:
        available: true
        disabled: false
        layout: sympal
        stylesheets:
          - /sfSympalThemePlugin/css/sympal.css
      
    # Configure the default theme to render Sympal with
    default_theme: default
      
    
    # Configure whether or not to allow the theme to be changed with a 
    # parameter in the url named sf_sympal_theme. Example: ?sf_sympal_theme=wordpress_default
    # The value will also be remembered in the users session
    allow_changing_theme_by_url: true
    theme_request_parameter_name: sf_sympal_theme