all:
  sympal_config:

    admin_modules:
      sympal_themes: ~

  theme:
    # Disable/Enable theming globally
    enabled:           true
    
    theme_class:       sfTheme             # Class that represents an individual theme
    manager_class:     sfThemeManager      # Class that handles the switching of themes
    controller_class:  sfThemeController   # Class that handles which theme should be chosen

    # Options for the controller - to help it choose the correct theme
    controller_options:
      default_theme:     default           # Configure the default theme to render
      admin_theme:       admin             # Configure the theme to render for "admin" modules
      
      modules:    []                       # Specify an array of modules and the theme that each should use
        # my_module:     theme_name
      routes:     []                       # Specify an array of routes and the theme that each should use
        # my_route:      theme_name

      # Configure whether or not to allow the theme to be changed with a 
      # parameter in the url named sf_sympal_theme. Example: ?sf_sympal_theme=wordpress_default
      # The value will also be remembered in the users session
      allow_changing_theme_by_url: true
      theme_request_parameter_name: sf_sympal_theme

    cache:
      enabled:  true
      class:    sfFileCache
      options:
        cache_dir:  <?php echo sfConfig::get('sf_app_cache_dir') ?>/theme

    themes:
      # my_theme:
      #   available: false       # Don't show in the list of available themes to switch to
      #   disabled: false
      #   layout:   my_theme
      #   admin_generator_class: sfSympalDoctrineGenerator
      #   admin_generator_theme: sympal_admin
      #   javascripts:
      #     - /sfSympalPlugin/js/jQuery.cookie.js
      #   stylesheets:
      #     - /sfSympalPlugin/fancybox/jquery.fancybox.css
      #   callables:
      #     - [sfSympalToolkit, useJQuery]
