parameters:
  
  theme_manager.class:        sfSympalThemeManager        # Responsible for managing themes
  
  theme_dispatcher.class:     sfSympalThemeDispatcher     # Responsible for determining the correct theme for a request, module, route, etc
  
services:

  theme_manager:
    class:                    %theme_manager.class%
    shared:                   true
    arguments:                [@controller, @request, @response]
  
  theme_dispatcher:
    class:                    %theme_dispatcher.class%
    shared:                   true
    arguments:                []